export const MESSAGE_TYPES = {
  EXTRACT_CURRENT_PAGE: 'EXTRACT_CURRENT_PAGE',
  GET_SELECTION: 'GET_SELECTION',
  GET_SETTINGS: 'GET_SETTINGS',
  SAVE_SETTINGS: 'SAVE_SETTINGS',
  SAVE_LAST_CLIP: 'SAVE_LAST_CLIP',
  GET_LAST_CLIP: 'GET_LAST_CLIP',
} as const

export type MessageTypeValue =
  (typeof MESSAGE_TYPES)[keyof typeof MESSAGE_TYPES]
