export class ClipMateError extends Error {
  constructor(
    message: string,
    public code: string = 'UNKNOWN',
  ) {
    super(message)
    this.name = 'ClipMateError'
  }
}

export const ErrorCodes = {
  NO_SELECTION: 'NO_SELECTION',
  EXTRACTION_FAILED: 'EXTRACTION_FAILED',
  STORAGE_ERROR: 'STORAGE_ERROR',
  NO_ACTIVE_TAB: 'NO_ACTIVE_TAB',
  METADATA_PARSE_FAILED: 'METADATA_PARSE_FAILED',
  NOTION_TOKEN_MISSING: 'NOTION_TOKEN_MISSING',
  NOTION_PAGE_ID_MISSING: 'NOTION_PAGE_ID_MISSING',
  NOTION_AUTH_FAILED: 'NOTION_AUTH_FAILED',
  NOTION_PAGE_NOT_FOUND: 'NOTION_PAGE_NOT_FOUND',
  NOTION_RATE_LIMITED: 'NOTION_RATE_LIMITED',
  NOTION_VALIDATION_ERROR: 'NOTION_VALIDATION_ERROR',
  NOTION_CONFLICT: 'NOTION_CONFLICT',
  NOTION_SERVICE_UNAVAILABLE: 'NOTION_SERVICE_UNAVAILABLE',
  NETWORK_ERROR: 'NETWORK_ERROR',
  NOTION_SAVE_FAILED: 'NOTION_SAVE_FAILED',
  CONTENT_EMPTY: 'CONTENT_EMPTY',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
