import type { SiteProfile } from './siteProfile.types'

export const SEED_PROFILES: readonly SiteProfile[] = [
  {
    id: 'google-search',
    label: 'Google Search',
    category: 'search',
    domains: ['google.com'],
    pageTypes: ['search-results'],
    priority: 10,
    selectorHints: {
      searchResultCard: '#search .g, #rso .g',
    },
  },
  {
    id: 'bing-search',
    label: 'Bing Search',
    category: 'search',
    domains: ['bing.com'],
    pageTypes: ['search-results'],
    priority: 10,
    selectorHints: {
      searchResultCard: '#b_results .b_algo',
    },
  },
  {
    id: 'baidu-search',
    label: 'Baidu Search',
    category: 'search',
    domains: ['baidu.com'],
    pageTypes: ['search-results'],
    priority: 10,
    selectorHints: {
      searchResultCard: '#content_left .result',
    },
  },
  {
    id: 'youtube-video',
    label: 'YouTube',
    category: 'video',
    domains: ['youtube.com', 'youtu.be'],
    pageTypes: ['video'],
    priority: 20,
    selectorHints: {
      contentContainer: '#above, #below',
      commentContainer: '#comments, ytd-comments',
      videoPlayer: '#movie_player, #player',
    },
  },
  {
    id: 'bilibili-video',
    label: 'Bilibili',
    category: 'video',
    domains: ['bilibili.com'],
    pageTypes: ['video'],
    priority: 20,
    selectorHints: {
      commentContainer: '.reply-list, .comment-list',
      videoPlayer: '#bilibiliPlayer, .bpx-player-video-wrap',
    },
  },
  {
    id: 'iqiyi-video',
    label: 'iQiyi',
    category: 'video',
    domains: ['iqiyi.com'],
    pageTypes: ['video'],
    priority: 15,
    selectorHints: {
      videoPlayer: '[data-player-hook], .iqp-player',
    },
  },
  {
    id: 'youku-video',
    label: 'Youku',
    category: 'video',
    domains: ['youku.com'],
    pageTypes: ['video'],
    priority: 15,
    selectorHints: {
      videoPlayer: '#youku-player, .yk-player',
    },
  },
  {
    id: 'tencent-video',
    label: 'Tencent Video',
    category: 'video',
    domains: ['v.qq.com'],
    pageTypes: ['video'],
    priority: 15,
    selectorHints: {
      videoPlayer: '#tenvideo_player, .txp_player',
    },
  },
  {
    id: 'tiktok-short-video',
    label: 'TikTok',
    category: 'short-video',
    domains: ['tiktok.com'],
    pageTypes: ['video'],
    priority: 20,
    selectorHints: {
      videoPlayer: '[data-e2e="video-player"], .video-player',
    },
  },
  {
    id: 'douyin-short-video',
    label: 'Douyin',
    category: 'short-video',
    domains: ['douyin.com'],
    pageTypes: ['video'],
    priority: 20,
    selectorHints: {
      videoPlayer: '.video-player, .xgplayer',
    },
  },
  {
    id: 'xiaohongshu-social',
    label: 'Xiaohongshu',
    category: 'social',
    domains: ['xiaohongshu.com'],
    pageTypes: ['article', 'forum-or-comment'],
    priority: 20,
    selectorHints: {
      contentContainer: '.note-content',
      commentContainer: '.comment-container',
    },
  },
  {
    id: 'kuaishou-short-video',
    label: 'Kuaishou',
    category: 'short-video',
    domains: ['kuaishou.com'],
    pageTypes: ['video'],
    priority: 15,
    selectorHints: {
      videoPlayer: '.player-container, .video-player',
    },
  },
  {
    id: 'zhihu-community',
    label: 'Zhihu',
    category: 'community',
    domains: ['zhihu.com'],
    pageTypes: ['article', 'forum-or-comment'],
    priority: 20,
    selectorHints: {
      contentContainer: '.QuestionAnswer-content, .RichContent',
      commentContainer: '.Comments-container',
    },
  },
  {
    id: 'reddit-community',
    label: 'Reddit',
    category: 'community',
    domains: ['reddit.com'],
    pageTypes: ['forum-or-comment', 'article'],
    priority: 20,
    selectorHints: {
      commentContainer: 'shreddit-comment, [slot="comment"]',
    },
  },
  {
    id: 'weibo-social',
    label: 'Weibo',
    category: 'social',
    domains: ['weibo.com'],
    pageTypes: ['forum-or-comment'],
    priority: 20,
    selectorHints: {
      contentContainer: '.WB_feed',
      commentContainer: '.comment_list',
    },
  },
  {
    id: 'chatgpt-ai-chat',
    label: 'ChatGPT',
    category: 'ai-chat',
    domains: ['chatgpt.com'],
    pageTypes: ['ai-answer'],
    priority: 25,
    selectorHints: {
      contentContainer: '[data-message-author-role]',
    },
  },
  {
    id: 'claude-ai-chat',
    label: 'Claude',
    category: 'ai-chat',
    domains: ['claude.ai'],
    pageTypes: ['ai-answer'],
    priority: 25,
  },
  {
    id: 'gemini-ai-chat',
    label: 'Gemini',
    category: 'ai-chat',
    domains: ['gemini.google.com'],
    pageTypes: ['ai-answer'],
    priority: 25,
  },
  {
    id: 'copilot-ai-chat',
    label: 'Copilot',
    category: 'ai-chat',
    domains: ['copilot.microsoft.com'],
    pageTypes: ['ai-answer'],
    priority: 25,
  },
]
