export const MESSAGE_TYPES = {
  EXTRACT_CURRENT_PAGE: 'EXTRACT_CURRENT_PAGE',
  EXTRACT_TUTORIAL: 'EXTRACT_TUTORIAL',
  GET_SELECTION: 'GET_SELECTION',
  GET_SETTINGS: 'GET_SETTINGS',
  SAVE_SETTINGS: 'SAVE_SETTINGS',
  SAVE_LAST_CLIP: 'SAVE_LAST_CLIP',
  GET_LAST_CLIP: 'GET_LAST_CLIP',
  SAVE_TO_NOTION: 'SAVE_TO_NOTION',
  START_ASSET_PICKER: 'START_ASSET_PICKER',
  GET_ASSET_PICKER_STATE: 'GET_ASSET_PICKER_STATE',
  CANCEL_ASSET_PICKER: 'CANCEL_ASSET_PICKER',
  CONSUME_ASSET_PICKER_RESULT: 'CONSUME_ASSET_PICKER_RESULT'
} as const

export type MessageTypeValue = (typeof MESSAGE_TYPES)[keyof typeof MESSAGE_TYPES]
